Search.appendIndex(
    [
                {
            "fqsen": "\\App\\Controllers\\Admin\\BaseController",
            "name": "BaseController",
            "summary": "Class\u0020BaseController",
            "url": "classes/App-Controllers-Admin-BaseController.html"
        },                {
            "fqsen": "\\App\\Controllers\\Admin\\BaseController\u003A\u003AinitController\u0028\u0029",
            "name": "initController",
            "summary": "",
            "url": "classes/App-Controllers-Admin-BaseController.html#method_initController"
        },                {
            "fqsen": "\\App\\Controllers\\Admin\\BaseController\u003A\u003Aget_live_route\u0028\u0029",
            "name": "get_live_route",
            "summary": "",
            "url": "classes/App-Controllers-Admin-BaseController.html#method_get_live_route"
        },                {
            "fqsen": "\\App\\Controllers\\Admin\\BaseController\u003A\u003A\u0024request",
            "name": "request",
            "summary": "Instance\u0020of\u0020the\u0020main\u0020Request\u0020object.",
            "url": "classes/App-Controllers-Admin-BaseController.html#property_request"
        },                {
            "fqsen": "\\App\\Controllers\\Admin\\BaseController\u003A\u003A\u0024data",
            "name": "data",
            "summary": "",
            "url": "classes/App-Controllers-Admin-BaseController.html#property_data"
        },                {
            "fqsen": "\\App\\Controllers\\Admin\\BaseController\u003A\u003A\u0024user",
            "name": "user",
            "summary": "",
            "url": "classes/App-Controllers-Admin-BaseController.html#property_user"
        },                {
            "fqsen": "\\App\\Controllers\\Admin\\BaseController\u003A\u003A\u0024helpers",
            "name": "helpers",
            "summary": "An\u0020array\u0020of\u0020helpers\u0020to\u0020be\u0020loaded\u0020automatically\u0020upon\nclass\u0020instantiation.\u0020These\u0020helpers\u0020will\u0020be\u0020available\nto\u0020all\u0020other\u0020controllers\u0020that\u0020extend\u0020BaseController.",
            "url": "classes/App-Controllers-Admin-BaseController.html#property_helpers"
        },                {
            "fqsen": "\\App\\Controllers\\Admin\\DashboardModules\\DashboardModule",
            "name": "DashboardModule",
            "summary": "Provides\u0020base\u0020class\u0020for\u0020modular\u0020dashboard\u0020modules",
            "url": "classes/App-Controllers-Admin-DashboardModules-DashboardModule.html"
        },                {
            "fqsen": "\\App\\Controllers\\Admin\\DashboardModules\\DashboardModule\u003A\u003AgetSort\u0028\u0029",
            "name": "getSort",
            "summary": "Returns\u0020sort\u0020order",
            "url": "classes/App-Controllers-Admin-DashboardModules-DashboardModule.html#method_getSort"
        },                {
            "fqsen": "\\App\\Controllers\\Admin\\DashboardModules\\DashboardModule\u003A\u003AgetCssClass\u0028\u0029",
            "name": "getCssClass",
            "summary": "Returns\u0020custom\u0020css\u0020class",
            "url": "classes/App-Controllers-Admin-DashboardModules-DashboardModule.html#method_getCssClass"
        },                {
            "fqsen": "\\App\\Controllers\\Admin\\DashboardModules\\DashboardModule\u003A\u003AgetVisibility\u0028\u0029",
            "name": "getVisibility",
            "summary": "Returns\u0020true\u0020if\u0020module\u0020is\u0020visible,\u0020false\u0020if\u0020not",
            "url": "classes/App-Controllers-Admin-DashboardModules-DashboardModule.html#method_getVisibility"
        },                {
            "fqsen": "\\App\\Controllers\\Admin\\DashboardModules\\DashboardModule\u003A\u003A\u0024data",
            "name": "data",
            "summary": "Used\u0020for\u0020the\u0020view",
            "url": "classes/App-Controllers-Admin-DashboardModules-DashboardModule.html#property_data"
        },                {
            "fqsen": "\\App\\Controllers\\Admin\\DashboardModules\\DashboardModule\u003A\u003A\u0024sort",
            "name": "sort",
            "summary": "Sort\u0020order",
            "url": "classes/App-Controllers-Admin-DashboardModules-DashboardModule.html#property_sort"
        },                {
            "fqsen": "\\App\\Controllers\\Admin\\DashboardModules\\DashboardModule\u003A\u003A\u0024css_class",
            "name": "css_class",
            "summary": "Custom\u0020css\u0020class",
            "url": "classes/App-Controllers-Admin-DashboardModules-DashboardModule.html#property_css_class"
        },                {
            "fqsen": "\\App\\Controllers\\Admin\\DashboardModules\\DashboardModule\u003A\u003A\u0024visible",
            "name": "visible",
            "summary": "Visiblity\u0020state,\u0020default\u0020is\u0020true",
            "url": "classes/App-Controllers-Admin-DashboardModules-DashboardModule.html#property_visible"
        },                {
            "fqsen": "\\App\\Controllers\\Admin\\DashboardModules\\DevicesDashboardModule",
            "name": "DevicesDashboardModule",
            "summary": "Dashboard\u0020Module",
            "url": "classes/App-Controllers-Admin-DashboardModules-DevicesDashboardModule.html"
        },                {
            "fqsen": "\\App\\Controllers\\Admin\\DashboardModules\\DevicesDashboardModule\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Controllers-Admin-DashboardModules-DevicesDashboardModule.html#method___construct"
        },                {
            "fqsen": "\\App\\Controllers\\Admin\\DashboardModules\\DevicesDashboardModule\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "",
            "url": "classes/App-Controllers-Admin-DashboardModules-DevicesDashboardModule.html#method_index"
        },                {
            "fqsen": "\\App\\Controllers\\Admin\\DashboardModules\\DevicesDashboardModule\u003A\u003A\u0024sort",
            "name": "sort",
            "summary": "Sort\u0020order",
            "url": "classes/App-Controllers-Admin-DashboardModules-DevicesDashboardModule.html#property_sort"
        },                {
            "fqsen": "\\App\\Controllers\\Admin\\DashboardModules\\DevicesDashboardModule\u003A\u003A\u0024css_class",
            "name": "css_class",
            "summary": "Custom\u0020css\u0020class",
            "url": "classes/App-Controllers-Admin-DashboardModules-DevicesDashboardModule.html#property_css_class"
        },                {
            "fqsen": "\\App\\Controllers\\Admin\\DashboardModules\\ExampleDashboardModule",
            "name": "ExampleDashboardModule",
            "summary": "Dashboard\u0020Module",
            "url": "classes/App-Controllers-Admin-DashboardModules-ExampleDashboardModule.html"
        },                {
            "fqsen": "\\App\\Controllers\\Admin\\DashboardModules\\ExampleDashboardModule\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "",
            "url": "classes/App-Controllers-Admin-DashboardModules-ExampleDashboardModule.html#method_index"
        },                {
            "fqsen": "\\App\\Controllers\\Admin\\DashboardModules\\ExampleDashboardModule\u003A\u003A\u0024sort",
            "name": "sort",
            "summary": "Sort\u0020order",
            "url": "classes/App-Controllers-Admin-DashboardModules-ExampleDashboardModule.html#property_sort"
        },                {
            "fqsen": "\\App\\Controllers\\Admin\\DashboardModules\\ExampleDashboardModule\u003A\u003A\u0024css_class",
            "name": "css_class",
            "summary": "Custom\u0020css\u0020class",
            "url": "classes/App-Controllers-Admin-DashboardModules-ExampleDashboardModule.html#property_css_class"
        },                {
            "fqsen": "\\App\\Controllers\\Admin\\DeviceController",
            "name": "DeviceController",
            "summary": "Class\u0020BaseController",
            "url": "classes/App-Controllers-Admin-DeviceController.html"
        },                {
            "fqsen": "\\App\\Controllers\\Admin\\DeviceController\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Controllers-Admin-DeviceController.html#method___construct"
        },                {
            "fqsen": "\\App\\Controllers\\Admin\\DeviceController\u003A\u003Aupdate\u0028\u0029",
            "name": "update",
            "summary": "",
            "url": "classes/App-Controllers-Admin-DeviceController.html#method_update"
        },                {
            "fqsen": "\\App\\Controllers\\Admin\\DeviceController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "",
            "url": "classes/App-Controllers-Admin-DeviceController.html#method_index"
        },                {
            "fqsen": "\\App\\Controllers\\Admin\\DeviceController\u003A\u003A\u0024deviceModel",
            "name": "deviceModel",
            "summary": "",
            "url": "classes/App-Controllers-Admin-DeviceController.html#property_deviceModel"
        },                {
            "fqsen": "\\App\\Controllers\\Admin\\DevicesController",
            "name": "DevicesController",
            "summary": "Class\u0020BaseController",
            "url": "classes/App-Controllers-Admin-DevicesController.html"
        },                {
            "fqsen": "\\App\\Controllers\\Admin\\DevicesController\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Controllers-Admin-DevicesController.html#method___construct"
        },                {
            "fqsen": "\\App\\Controllers\\Admin\\DevicesController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "",
            "url": "classes/App-Controllers-Admin-DevicesController.html#method_index"
        },                {
            "fqsen": "\\App\\Controllers\\Admin\\DevicesController\u003A\u003A\u0024deviceModel",
            "name": "deviceModel",
            "summary": "",
            "url": "classes/App-Controllers-Admin-DevicesController.html#property_deviceModel"
        },                {
            "fqsen": "\\App\\Controllers\\Admin\\FilesController",
            "name": "FilesController",
            "summary": "Class\u0020BaseController",
            "url": "classes/App-Controllers-Admin-FilesController.html"
        },                {
            "fqsen": "\\App\\Controllers\\Admin\\FilesController\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Controllers-Admin-FilesController.html#method___construct"
        },                {
            "fqsen": "\\App\\Controllers\\Admin\\FilesController\u003A\u003Aload_uploaded_files\u0028\u0029",
            "name": "load_uploaded_files",
            "summary": "",
            "url": "classes/App-Controllers-Admin-FilesController.html#method_load_uploaded_files"
        },                {
            "fqsen": "\\App\\Controllers\\Admin\\FilesController\u003A\u003Aload_common_data\u0028\u0029",
            "name": "load_common_data",
            "summary": "",
            "url": "classes/App-Controllers-Admin-FilesController.html#method_load_common_data"
        },                {
            "fqsen": "\\App\\Controllers\\Admin\\FilesController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "",
            "url": "classes/App-Controllers-Admin-FilesController.html#method_index"
        },                {
            "fqsen": "\\App\\Controllers\\Admin\\FilesController\u003A\u003Adelete_file\u0028\u0029",
            "name": "delete_file",
            "summary": "",
            "url": "classes/App-Controllers-Admin-FilesController.html#method_delete_file"
        },                {
            "fqsen": "\\App\\Controllers\\Admin\\FilesController\u003A\u003Averify_upload_directory\u0028\u0029",
            "name": "verify_upload_directory",
            "summary": "verifies\u0020or\u0020creates\u0020the\u0020requested\u0020upload\u0020direcory",
            "url": "classes/App-Controllers-Admin-FilesController.html#method_verify_upload_directory"
        },                {
            "fqsen": "\\App\\Controllers\\Admin\\FilesController\u003A\u003Aupload\u0028\u0029",
            "name": "upload",
            "summary": "",
            "url": "classes/App-Controllers-Admin-FilesController.html#method_upload"
        },                {
            "fqsen": "\\App\\Controllers\\Admin\\FilesController\u003A\u003A\u0024uploads",
            "name": "uploads",
            "summary": "",
            "url": "classes/App-Controllers-Admin-FilesController.html#property_uploads"
        },                {
            "fqsen": "\\App\\Controllers\\Admin\\Home",
            "name": "Home",
            "summary": "Class\u0020BaseController",
            "url": "classes/App-Controllers-Admin-Home.html"
        },                {
            "fqsen": "\\App\\Controllers\\Admin\\Home\u003A\u003Adashboard\u0028\u0029",
            "name": "dashboard",
            "summary": "",
            "url": "classes/App-Controllers-Admin-Home.html#method_dashboard"
        },                {
            "fqsen": "\\App\\Controllers\\Admin\\UserController",
            "name": "UserController",
            "summary": "Class\u0020BaseController",
            "url": "classes/App-Controllers-Admin-UserController.html"
        },                {
            "fqsen": "\\App\\Controllers\\Admin\\UserController\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Controllers-Admin-UserController.html#method___construct"
        },                {
            "fqsen": "\\App\\Controllers\\Admin\\UserController\u003A\u003Anew_user\u0028\u0029",
            "name": "new_user",
            "summary": "",
            "url": "classes/App-Controllers-Admin-UserController.html#method_new_user"
        },                {
            "fqsen": "\\App\\Controllers\\Admin\\UserController\u003A\u003AgenerateUniqueUsername\u0028\u0029",
            "name": "generateUniqueUsername",
            "summary": "Create\u0020a\u0020random\u0020unique\u0020username",
            "url": "classes/App-Controllers-Admin-UserController.html#method_generateUniqueUsername"
        },                {
            "fqsen": "\\App\\Controllers\\Admin\\UserController\u003A\u003Anew_user_create\u0028\u0029",
            "name": "new_user_create",
            "summary": "Create\u0020new\u0020user",
            "url": "classes/App-Controllers-Admin-UserController.html#method_new_user_create"
        },                {
            "fqsen": "\\App\\Controllers\\Admin\\UserController\u003A\u003Aupdate\u0028\u0029",
            "name": "update",
            "summary": "",
            "url": "classes/App-Controllers-Admin-UserController.html#method_update"
        },                {
            "fqsen": "\\App\\Controllers\\Admin\\UserController\u003A\u003Adelete\u0028\u0029",
            "name": "delete",
            "summary": "",
            "url": "classes/App-Controllers-Admin-UserController.html#method_delete"
        },                {
            "fqsen": "\\App\\Controllers\\Admin\\UserController\u003A\u003Achange_password\u0028\u0029",
            "name": "change_password",
            "summary": "",
            "url": "classes/App-Controllers-Admin-UserController.html#method_change_password"
        },                {
            "fqsen": "\\App\\Controllers\\Admin\\UserController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "",
            "url": "classes/App-Controllers-Admin-UserController.html#method_index"
        },                {
            "fqsen": "\\App\\Controllers\\Admin\\UserController\u003A\u003AgetUserProvider\u0028\u0029",
            "name": "getUserProvider",
            "summary": "Returns\u0020the\u0020User\u0020provider",
            "url": "classes/App-Controllers-Admin-UserController.html#method_getUserProvider"
        },                {
            "fqsen": "\\App\\Controllers\\Admin\\UserController\u003A\u003AgetValidationRules\u0028\u0029",
            "name": "getValidationRules",
            "summary": "Returns\u0020the\u0020rules\u0020that\u0020should\u0020be\u0020used\u0020for\u0020validation.",
            "url": "classes/App-Controllers-Admin-UserController.html#method_getValidationRules"
        },                {
            "fqsen": "\\App\\Controllers\\Admin\\UserController\u003A\u003A\u0024userModel",
            "name": "userModel",
            "summary": "",
            "url": "classes/App-Controllers-Admin-UserController.html#property_userModel"
        },                {
            "fqsen": "\\App\\Controllers\\Admin\\UsersController",
            "name": "UsersController",
            "summary": "Class\u0020BaseController",
            "url": "classes/App-Controllers-Admin-UsersController.html"
        },                {
            "fqsen": "\\App\\Controllers\\Admin\\UsersController\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Controllers-Admin-UsersController.html#method___construct"
        },                {
            "fqsen": "\\App\\Controllers\\Admin\\UsersController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "",
            "url": "classes/App-Controllers-Admin-UsersController.html#method_index"
        },                {
            "fqsen": "\\App\\Controllers\\Admin\\UsersController\u003A\u003A\u0024userModel",
            "name": "userModel",
            "summary": "",
            "url": "classes/App-Controllers-Admin-UsersController.html#property_userModel"
        },                {
            "fqsen": "\\App\\Controllers\\BaseController",
            "name": "BaseController",
            "summary": "Class\u0020BaseController",
            "url": "classes/App-Controllers-BaseController.html"
        },                {
            "fqsen": "\\App\\Controllers\\BaseController\u003A\u003AinitController\u0028\u0029",
            "name": "initController",
            "summary": "",
            "url": "classes/App-Controllers-BaseController.html#method_initController"
        },                {
            "fqsen": "\\App\\Controllers\\BaseController\u003A\u003A\u0024request",
            "name": "request",
            "summary": "Instance\u0020of\u0020the\u0020main\u0020Request\u0020object.",
            "url": "classes/App-Controllers-BaseController.html#property_request"
        },                {
            "fqsen": "\\App\\Controllers\\BaseController\u003A\u003A\u0024helpers",
            "name": "helpers",
            "summary": "An\u0020array\u0020of\u0020helpers\u0020to\u0020be\u0020loaded\u0020automatically\u0020upon\nclass\u0020instantiation.\u0020These\u0020helpers\u0020will\u0020be\u0020available\nto\u0020all\u0020other\u0020controllers\u0020that\u0020extend\u0020BaseController.",
            "url": "classes/App-Controllers-BaseController.html#property_helpers"
        },                {
            "fqsen": "\\App\\Controllers\\DeviceControler",
            "name": "DeviceControler",
            "summary": "Class\u0020BaseController",
            "url": "classes/App-Controllers-DeviceControler.html"
        },                {
            "fqsen": "\\App\\Controllers\\DeviceControler\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Controllers-DeviceControler.html#method___construct"
        },                {
            "fqsen": "\\App\\Controllers\\DeviceControler\u003A\u003Aget_stats\u0028\u0029",
            "name": "get_stats",
            "summary": "",
            "url": "classes/App-Controllers-DeviceControler.html#method_get_stats"
        },                {
            "fqsen": "\\App\\Controllers\\DeviceControler\u003A\u003Areceive\u0028\u0029",
            "name": "receive",
            "summary": "",
            "url": "classes/App-Controllers-DeviceControler.html#method_receive"
        },                {
            "fqsen": "\\App\\Controllers\\DeviceControler\u003A\u003Aregister\u0028\u0029",
            "name": "register",
            "summary": "",
            "url": "classes/App-Controllers-DeviceControler.html#method_register"
        },                {
            "fqsen": "\\App\\Controllers\\Front\\BaseController",
            "name": "BaseController",
            "summary": "Class\u0020BaseController",
            "url": "classes/App-Controllers-Front-BaseController.html"
        },                {
            "fqsen": "\\App\\Controllers\\Front\\BaseController\u003A\u003AinitSessionController\u0028\u0029",
            "name": "initSessionController",
            "summary": "",
            "url": "classes/App-Controllers-Front-BaseController.html#method_initSessionController"
        },                {
            "fqsen": "\\App\\Controllers\\Front\\BaseController\u003A\u003AinitController\u0028\u0029",
            "name": "initController",
            "summary": "",
            "url": "classes/App-Controllers-Front-BaseController.html#method_initController"
        },                {
            "fqsen": "\\App\\Controllers\\Front\\BaseController\u003A\u003A\u0024request",
            "name": "request",
            "summary": "Instance\u0020of\u0020the\u0020main\u0020Request\u0020object.",
            "url": "classes/App-Controllers-Front-BaseController.html#property_request"
        },                {
            "fqsen": "\\App\\Controllers\\Front\\BaseController\u003A\u003A\u0024data",
            "name": "data",
            "summary": "",
            "url": "classes/App-Controllers-Front-BaseController.html#property_data"
        },                {
            "fqsen": "\\App\\Controllers\\Front\\BaseController\u003A\u003A\u0024user",
            "name": "user",
            "summary": "",
            "url": "classes/App-Controllers-Front-BaseController.html#property_user"
        },                {
            "fqsen": "\\App\\Controllers\\Front\\BaseController\u003A\u003A\u0024helpers",
            "name": "helpers",
            "summary": "An\u0020array\u0020of\u0020helpers\u0020to\u0020be\u0020loaded\u0020automatically\u0020upon\nclass\u0020instantiation.\u0020These\u0020helpers\u0020will\u0020be\u0020available\nto\u0020all\u0020other\u0020controllers\u0020that\u0020extend\u0020BaseController.",
            "url": "classes/App-Controllers-Front-BaseController.html#property_helpers"
        },                {
            "fqsen": "\\App\\Controllers\\Front\\DashboardModules\\DashboardModule",
            "name": "DashboardModule",
            "summary": "Provides\u0020base\u0020class\u0020for\u0020modular\u0020dashboard\u0020modules",
            "url": "classes/App-Controllers-Front-DashboardModules-DashboardModule.html"
        },                {
            "fqsen": "\\App\\Controllers\\Front\\DashboardModules\\DashboardModule\u003A\u003AgetSort\u0028\u0029",
            "name": "getSort",
            "summary": "Returns\u0020sort\u0020order",
            "url": "classes/App-Controllers-Front-DashboardModules-DashboardModule.html#method_getSort"
        },                {
            "fqsen": "\\App\\Controllers\\Front\\DashboardModules\\DashboardModule\u003A\u003AgetCssClass\u0028\u0029",
            "name": "getCssClass",
            "summary": "Returns\u0020custom\u0020css\u0020class",
            "url": "classes/App-Controllers-Front-DashboardModules-DashboardModule.html#method_getCssClass"
        },                {
            "fqsen": "\\App\\Controllers\\Front\\DashboardModules\\DashboardModule\u003A\u003AgetVisibility\u0028\u0029",
            "name": "getVisibility",
            "summary": "Returns\u0020true\u0020if\u0020module\u0020is\u0020visible,\u0020false\u0020if\u0020not",
            "url": "classes/App-Controllers-Front-DashboardModules-DashboardModule.html#method_getVisibility"
        },                {
            "fqsen": "\\App\\Controllers\\Front\\DashboardModules\\DashboardModule\u003A\u003A\u0024data",
            "name": "data",
            "summary": "Used\u0020for\u0020the\u0020view",
            "url": "classes/App-Controllers-Front-DashboardModules-DashboardModule.html#property_data"
        },                {
            "fqsen": "\\App\\Controllers\\Front\\DashboardModules\\DashboardModule\u003A\u003A\u0024sort",
            "name": "sort",
            "summary": "Sort\u0020order",
            "url": "classes/App-Controllers-Front-DashboardModules-DashboardModule.html#property_sort"
        },                {
            "fqsen": "\\App\\Controllers\\Front\\DashboardModules\\DashboardModule\u003A\u003A\u0024css_class",
            "name": "css_class",
            "summary": "Custom\u0020css\u0020class",
            "url": "classes/App-Controllers-Front-DashboardModules-DashboardModule.html#property_css_class"
        },                {
            "fqsen": "\\App\\Controllers\\Front\\DashboardModules\\DashboardModule\u003A\u003A\u0024visible",
            "name": "visible",
            "summary": "Visiblity\u0020state,\u0020default\u0020is\u0020true",
            "url": "classes/App-Controllers-Front-DashboardModules-DashboardModule.html#property_visible"
        },                {
            "fqsen": "\\App\\Controllers\\Front\\DashboardModules\\DevicesDashboardModule",
            "name": "DevicesDashboardModule",
            "summary": "Dashboard\u0020Module",
            "url": "classes/App-Controllers-Front-DashboardModules-DevicesDashboardModule.html"
        },                {
            "fqsen": "\\App\\Controllers\\Front\\DashboardModules\\DevicesDashboardModule\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Controllers-Front-DashboardModules-DevicesDashboardModule.html#method___construct"
        },                {
            "fqsen": "\\App\\Controllers\\Front\\DashboardModules\\DevicesDashboardModule\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "",
            "url": "classes/App-Controllers-Front-DashboardModules-DevicesDashboardModule.html#method_index"
        },                {
            "fqsen": "\\App\\Controllers\\Front\\DashboardModules\\DevicesDashboardModule\u003A\u003A\u0024sort",
            "name": "sort",
            "summary": "Sort\u0020order",
            "url": "classes/App-Controllers-Front-DashboardModules-DevicesDashboardModule.html#property_sort"
        },                {
            "fqsen": "\\App\\Controllers\\Front\\DashboardModules\\DevicesDashboardModule\u003A\u003A\u0024css_class",
            "name": "css_class",
            "summary": "Custom\u0020css\u0020class",
            "url": "classes/App-Controllers-Front-DashboardModules-DevicesDashboardModule.html#property_css_class"
        },                {
            "fqsen": "\\App\\Controllers\\Front\\DownloadController",
            "name": "DownloadController",
            "summary": "Class\u0020BaseController",
            "url": "classes/App-Controllers-Front-DownloadController.html"
        },                {
            "fqsen": "\\App\\Controllers\\Front\\DownloadController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "",
            "url": "classes/App-Controllers-Front-DownloadController.html#method_index"
        },                {
            "fqsen": "\\App\\Controllers\\Front\\FilesController",
            "name": "FilesController",
            "summary": "Class\u0020BaseController",
            "url": "classes/App-Controllers-Front-FilesController.html"
        },                {
            "fqsen": "\\App\\Controllers\\Front\\FilesController\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Controllers-Front-FilesController.html#method___construct"
        },                {
            "fqsen": "\\App\\Controllers\\Front\\FilesController\u003A\u003Aload_uploaded_files\u0028\u0029",
            "name": "load_uploaded_files",
            "summary": "",
            "url": "classes/App-Controllers-Front-FilesController.html#method_load_uploaded_files"
        },                {
            "fqsen": "\\App\\Controllers\\Front\\FilesController\u003A\u003Aload_common_data\u0028\u0029",
            "name": "load_common_data",
            "summary": "",
            "url": "classes/App-Controllers-Front-FilesController.html#method_load_common_data"
        },                {
            "fqsen": "\\App\\Controllers\\Front\\FilesController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "",
            "url": "classes/App-Controllers-Front-FilesController.html#method_index"
        },                {
            "fqsen": "\\App\\Controllers\\Front\\FilesController\u003A\u003Adelete_file\u0028\u0029",
            "name": "delete_file",
            "summary": "",
            "url": "classes/App-Controllers-Front-FilesController.html#method_delete_file"
        },                {
            "fqsen": "\\App\\Controllers\\Front\\FilesController\u003A\u003Averify_upload_directory\u0028\u0029",
            "name": "verify_upload_directory",
            "summary": "verifies\u0020or\u0020creates\u0020the\u0020requested\u0020upload\u0020direcory",
            "url": "classes/App-Controllers-Front-FilesController.html#method_verify_upload_directory"
        },                {
            "fqsen": "\\App\\Controllers\\Front\\FilesController\u003A\u003Aupload\u0028\u0029",
            "name": "upload",
            "summary": "",
            "url": "classes/App-Controllers-Front-FilesController.html#method_upload"
        },                {
            "fqsen": "\\App\\Controllers\\Front\\FilesController\u003A\u003A\u0024uploads",
            "name": "uploads",
            "summary": "",
            "url": "classes/App-Controllers-Front-FilesController.html#property_uploads"
        },                {
            "fqsen": "\\App\\Controllers\\Front\\Home",
            "name": "Home",
            "summary": "Class\u0020BaseController",
            "url": "classes/App-Controllers-Front-Home.html"
        },                {
            "fqsen": "\\App\\Controllers\\Front\\Home\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "",
            "url": "classes/App-Controllers-Front-Home.html#method_index"
        },                {
            "fqsen": "\\App\\Controllers\\Front\\Home\u003A\u003Aapplication\u0028\u0029",
            "name": "application",
            "summary": "",
            "url": "classes/App-Controllers-Front-Home.html#method_application"
        },                {
            "fqsen": "\\App\\Controllers\\HardwareInfo",
            "name": "HardwareInfo",
            "summary": "Class\u0020BaseController",
            "url": "classes/App-Controllers-HardwareInfo.html"
        },                {
            "fqsen": "\\App\\Controllers\\HardwareInfo\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "",
            "url": "classes/App-Controllers-HardwareInfo.html#method_index"
        },                {
            "fqsen": "\\App\\Controllers\\LoginController",
            "name": "LoginController",
            "summary": "",
            "url": "classes/App-Controllers-LoginController.html"
        },                {
            "fqsen": "\\App\\Controllers\\LoginController\u003A\u003AloginView\u0028\u0029",
            "name": "loginView",
            "summary": "",
            "url": "classes/App-Controllers-LoginController.html#method_loginView"
        },                {
            "fqsen": "\\App\\Filters\\AuthFilterAdmin",
            "name": "AuthFilterAdmin",
            "summary": "",
            "url": "classes/App-Filters-AuthFilterAdmin.html"
        },                {
            "fqsen": "\\App\\Filters\\AuthFilterAdmin\u003A\u003Abefore\u0028\u0029",
            "name": "before",
            "summary": "",
            "url": "classes/App-Filters-AuthFilterAdmin.html#method_before"
        },                {
            "fqsen": "\\App\\Filters\\AuthFilterAdmin\u003A\u003Aafter\u0028\u0029",
            "name": "after",
            "summary": "",
            "url": "classes/App-Filters-AuthFilterAdmin.html#method_after"
        },                {
            "fqsen": "\\App\\Filters\\AuthFilterAdmin\u003A\u003A\u0024methods",
            "name": "methods",
            "summary": "",
            "url": "classes/App-Filters-AuthFilterAdmin.html#property_methods"
        },                {
            "fqsen": "\\App\\Filters\\AuthFilterGuest",
            "name": "AuthFilterGuest",
            "summary": "",
            "url": "classes/App-Filters-AuthFilterGuest.html"
        },                {
            "fqsen": "\\App\\Filters\\AuthFilterGuest\u003A\u003Abefore\u0028\u0029",
            "name": "before",
            "summary": "",
            "url": "classes/App-Filters-AuthFilterGuest.html#method_before"
        },                {
            "fqsen": "\\App\\Filters\\AuthFilterGuest\u003A\u003Aafter\u0028\u0029",
            "name": "after",
            "summary": "",
            "url": "classes/App-Filters-AuthFilterGuest.html#method_after"
        },                {
            "fqsen": "\\App\\Filters\\AuthFilterSession",
            "name": "AuthFilterSession",
            "summary": "",
            "url": "classes/App-Filters-AuthFilterSession.html"
        },                {
            "fqsen": "\\App\\Filters\\AuthFilterSession\u003A\u003Abefore\u0028\u0029",
            "name": "before",
            "summary": "",
            "url": "classes/App-Filters-AuthFilterSession.html#method_before"
        },                {
            "fqsen": "\\App\\Filters\\AuthFilterSession\u003A\u003Aafter\u0028\u0029",
            "name": "after",
            "summary": "",
            "url": "classes/App-Filters-AuthFilterSession.html#method_after"
        },                {
            "fqsen": "\\load_footer\u0028\u0029",
            "name": "load_footer",
            "summary": "",
            "url": "namespaces/default.html#function_load_footer"
        },                {
            "fqsen": "\\load_header\u0028\u0029",
            "name": "load_header",
            "summary": "",
            "url": "namespaces/default.html#function_load_header"
        },                {
            "fqsen": "\\setCSRFHeaderMeta\u0028\u0029",
            "name": "setCSRFHeaderMeta",
            "summary": "",
            "url": "namespaces/default.html#function_setCSRFHeaderMeta"
        },                {
            "fqsen": "\\updateCSRFMeta\u0028\u0029",
            "name": "updateCSRFMeta",
            "summary": "",
            "url": "namespaces/default.html#function_updateCSRFMeta"
        },                {
            "fqsen": "\\setCSRFPostData\u0028\u0029",
            "name": "setCSRFPostData",
            "summary": "",
            "url": "namespaces/default.html#function_setCSRFPostData"
        },                {
            "fqsen": "\\deviceUpdateHandlerJS\u0028\u0029",
            "name": "deviceUpdateHandlerJS",
            "summary": "",
            "url": "namespaces/default.html#function_deviceUpdateHandlerJS"
        },                {
            "fqsen": "\\download_url\u0028\u0029",
            "name": "download_url",
            "summary": "",
            "url": "namespaces/default.html#function_download_url"
        },                {
            "fqsen": "\\readable_filesize\u0028\u0029",
            "name": "readable_filesize",
            "summary": "",
            "url": "namespaces/default.html#function_readable_filesize"
        },                {
            "fqsen": "\\getSubclassesOf\u0028\u0029",
            "name": "getSubclassesOf",
            "summary": "",
            "url": "namespaces/default.html#function_getSubclassesOf"
        },                {
            "fqsen": "\\get_dashboard_modules\u0028\u0029",
            "name": "get_dashboard_modules",
            "summary": "",
            "url": "namespaces/default.html#function_get_dashboard_modules"
        },                {
            "fqsen": "\\generateUserShortName\u0028\u0029",
            "name": "generateUserShortName",
            "summary": "",
            "url": "namespaces/default.html#function_generateUserShortName"
        },                {
            "fqsen": "\\generateUserFullName\u0028\u0029",
            "name": "generateUserFullName",
            "summary": "",
            "url": "namespaces/default.html#function_generateUserFullName"
        },                {
            "fqsen": "\\App\\Models\\DeviceMeta",
            "name": "DeviceMeta",
            "summary": "",
            "url": "classes/App-Models-DeviceMeta.html"
        },                {
            "fqsen": "\\App\\Models\\DeviceMeta\u003A\u003A\u0024table",
            "name": "table",
            "summary": "",
            "url": "classes/App-Models-DeviceMeta.html#property_table"
        },                {
            "fqsen": "\\App\\Models\\DeviceMeta\u003A\u003A\u0024primaryKey",
            "name": "primaryKey",
            "summary": "",
            "url": "classes/App-Models-DeviceMeta.html#property_primaryKey"
        },                {
            "fqsen": "\\App\\Models\\DeviceMeta\u003A\u003A\u0024allowedFields",
            "name": "allowedFields",
            "summary": "",
            "url": "classes/App-Models-DeviceMeta.html#property_allowedFields"
        },                {
            "fqsen": "\\App\\Models\\Devices",
            "name": "Devices",
            "summary": "",
            "url": "classes/App-Models-Devices.html"
        },                {
            "fqsen": "\\App\\Models\\Devices\u003A\u003AgetDevices\u0028\u0029",
            "name": "getDevices",
            "summary": "",
            "url": "classes/App-Models-Devices.html#method_getDevices"
        },                {
            "fqsen": "\\App\\Models\\Devices\u003A\u003A\u0024table",
            "name": "table",
            "summary": "",
            "url": "classes/App-Models-Devices.html#property_table"
        },                {
            "fqsen": "\\App\\Models\\Devices\u003A\u003A\u0024primaryKey",
            "name": "primaryKey",
            "summary": "",
            "url": "classes/App-Models-Devices.html#property_primaryKey"
        },                {
            "fqsen": "\\App\\Models\\Devices\u003A\u003A\u0024allowedFields",
            "name": "allowedFields",
            "summary": "",
            "url": "classes/App-Models-Devices.html#property_allowedFields"
        },                {
            "fqsen": "\\App\\Models\\Protocol27",
            "name": "Protocol27",
            "summary": "",
            "url": "classes/App-Models-Protocol27.html"
        },                {
            "fqsen": "\\App\\Models\\Protocol27\u003A\u003A\u0024table",
            "name": "table",
            "summary": "",
            "url": "classes/App-Models-Protocol27.html#property_table"
        },                {
            "fqsen": "\\App\\Models\\Protocol27\u003A\u003A\u0024primaryKey",
            "name": "primaryKey",
            "summary": "",
            "url": "classes/App-Models-Protocol27.html#property_primaryKey"
        },                {
            "fqsen": "\\App\\Models\\Protocol27\u003A\u003A\u0024allowedFields",
            "name": "allowedFields",
            "summary": "",
            "url": "classes/App-Models-Protocol27.html#property_allowedFields"
        },                {
            "fqsen": "\\App\\Models\\Uploads",
            "name": "Uploads",
            "summary": "",
            "url": "classes/App-Models-Uploads.html"
        },                {
            "fqsen": "\\App\\Models\\Uploads\u003A\u003A\u0024table",
            "name": "table",
            "summary": "",
            "url": "classes/App-Models-Uploads.html#property_table"
        },                {
            "fqsen": "\\App\\Models\\Uploads\u003A\u003A\u0024primaryKey",
            "name": "primaryKey",
            "summary": "",
            "url": "classes/App-Models-Uploads.html#property_primaryKey"
        },                {
            "fqsen": "\\App\\Models\\Uploads\u003A\u003A\u0024allowedFields",
            "name": "allowedFields",
            "summary": "",
            "url": "classes/App-Models-Uploads.html#property_allowedFields"
        },                {
            "fqsen": "\\App\\Models\\User",
            "name": "User",
            "summary": "",
            "url": "classes/App-Models-User.html"
        },                {
            "fqsen": "\\App\\Models\\User\u003A\u003AgetFullUserData\u0028\u0029",
            "name": "getFullUserData",
            "summary": "",
            "url": "classes/App-Models-User.html#method_getFullUserData"
        },                {
            "fqsen": "\\App\\Models\\User\u003A\u003AgetUserInfo\u0028\u0029",
            "name": "getUserInfo",
            "summary": "",
            "url": "classes/App-Models-User.html#method_getUserInfo"
        },                {
            "fqsen": "\\App\\Models\\User\u003A\u003AisLoggedIn\u0028\u0029",
            "name": "isLoggedIn",
            "summary": "",
            "url": "classes/App-Models-User.html#method_isLoggedIn"
        },                {
            "fqsen": "\\App\\Models\\User\u003A\u003AisAdmin\u0028\u0029",
            "name": "isAdmin",
            "summary": "",
            "url": "classes/App-Models-User.html#method_isAdmin"
        },                {
            "fqsen": "\\App\\Models\\UserMeta",
            "name": "UserMeta",
            "summary": "",
            "url": "classes/App-Models-UserMeta.html"
        },                {
            "fqsen": "\\App\\Models\\UserMeta\u003A\u003A\u0024table",
            "name": "table",
            "summary": "",
            "url": "classes/App-Models-UserMeta.html#property_table"
        },                {
            "fqsen": "\\App\\Models\\UserMeta\u003A\u003A\u0024primaryKey",
            "name": "primaryKey",
            "summary": "",
            "url": "classes/App-Models-UserMeta.html#property_primaryKey"
        },                {
            "fqsen": "\\App\\Models\\UserMeta\u003A\u003A\u0024allowedFields",
            "name": "allowedFields",
            "summary": "",
            "url": "classes/App-Models-UserMeta.html#property_allowedFields"
        },                {
            "fqsen": "\\App\\Models\\Users",
            "name": "Users",
            "summary": "",
            "url": "classes/App-Models-Users.html"
        },                {
            "fqsen": "\\App\\Models\\Users\u003A\u003AgetUser\u0028\u0029",
            "name": "getUser",
            "summary": "",
            "url": "classes/App-Models-Users.html#method_getUser"
        },                {
            "fqsen": "\\App\\Models\\Users\u003A\u003AgetUsers\u0028\u0029",
            "name": "getUsers",
            "summary": "",
            "url": "classes/App-Models-Users.html#method_getUsers"
        },                {
            "fqsen": "\\App\\Models\\Users\u003A\u003A\u0024table",
            "name": "table",
            "summary": "",
            "url": "classes/App-Models-Users.html#property_table"
        },                {
            "fqsen": "\\App\\Models\\Users\u003A\u003A\u0024primaryKey",
            "name": "primaryKey",
            "summary": "",
            "url": "classes/App-Models-Users.html#property_primaryKey"
        },                {
            "fqsen": "\\App\\Models\\Users\u003A\u003A\u0024allowedFields",
            "name": "allowedFields",
            "summary": "",
            "url": "classes/App-Models-Users.html#property_allowedFields"
        },                {
            "fqsen": "\\App\\Services\\DeviceService",
            "name": "DeviceService",
            "summary": "Provides\u0020service\u0020to\u0020store\u0020user\u0020meta",
            "url": "classes/App-Services-DeviceService.html"
        },                {
            "fqsen": "\\App\\Services\\DeviceService\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "This\u0020method\u0020initializes\u0020the\u0020\u0060User\u0060\u0020object,\u0020retrieves\u0020the\u0020user\u0027s\u0020information,\u0020and\u0020ensures\u0020the\u0020user\u0020is\u0020valid.",
            "url": "classes/App-Services-DeviceService.html#method___construct"
        },                {
            "fqsen": "\\App\\Services\\DeviceService\u003A\u003Aload_devices_stats\u0028\u0029",
            "name": "load_devices_stats",
            "summary": "",
            "url": "classes/App-Services-DeviceService.html#method_load_devices_stats"
        },                {
            "fqsen": "\\App\\Services\\DeviceService\u003A\u003AgetDevices\u0028\u0029",
            "name": "getDevices",
            "summary": "",
            "url": "classes/App-Services-DeviceService.html#method_getDevices"
        },                {
            "fqsen": "\\App\\Services\\HardwareService",
            "name": "HardwareService",
            "summary": "Provides\u0020service\u0020to\u0020store\u0020user\u0020meta",
            "url": "classes/App-Services-HardwareService.html"
        },                {
            "fqsen": "\\App\\Services\\HardwareService\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "This\u0020method\u0020initializes\u0020the\u0020\u0060User\u0060\u0020object,\u0020retrieves\u0020the\u0020user\u0027s\u0020information,\u0020and\u0020ensures\u0020the\u0020user\u0020is\u0020valid.",
            "url": "classes/App-Services-HardwareService.html#method___construct"
        },                {
            "fqsen": "\\App\\Services\\HardwareService\u003A\u003AconvertKb\u0028\u0029",
            "name": "convertKb",
            "summary": "",
            "url": "classes/App-Services-HardwareService.html#method_convertKb"
        },                {
            "fqsen": "\\App\\Services\\HardwareService\u003A\u003AreadCpuStats\u0028\u0029",
            "name": "readCpuStats",
            "summary": "",
            "url": "classes/App-Services-HardwareService.html#method_readCpuStats"
        },                {
            "fqsen": "\\App\\Services\\HardwareService\u003A\u003AgetPerCoreCPULoad\u0028\u0029",
            "name": "getPerCoreCPULoad",
            "summary": "",
            "url": "classes/App-Services-HardwareService.html#method_getPerCoreCPULoad"
        },                {
            "fqsen": "\\App\\Services\\HardwareService\u003A\u003AgetOSVersion\u0028\u0029",
            "name": "getOSVersion",
            "summary": "",
            "url": "classes/App-Services-HardwareService.html#method_getOSVersion"
        },                {
            "fqsen": "\\App\\Services\\HardwareService\u003A\u003AgetHWVersion\u0028\u0029",
            "name": "getHWVersion",
            "summary": "",
            "url": "classes/App-Services-HardwareService.html#method_getHWVersion"
        },                {
            "fqsen": "\\App\\Services\\HardwareService\u003A\u003AgetCPUTemperature\u0028\u0029",
            "name": "getCPUTemperature",
            "summary": "",
            "url": "classes/App-Services-HardwareService.html#method_getCPUTemperature"
        },                {
            "fqsen": "\\App\\Services\\HardwareService\u003A\u003AgetMemoryUsage\u0028\u0029",
            "name": "getMemoryUsage",
            "summary": "",
            "url": "classes/App-Services-HardwareService.html#method_getMemoryUsage"
        },                {
            "fqsen": "\\App\\Services\\HardwareService\u003A\u003AgetAll\u0028\u0029",
            "name": "getAll",
            "summary": "",
            "url": "classes/App-Services-HardwareService.html#method_getAll"
        },                {
            "fqsen": "\\App\\Services\\HardwareService\u003A\u003A\u0024linux",
            "name": "linux",
            "summary": "",
            "url": "classes/App-Services-HardwareService.html#property_linux"
        },                {
            "fqsen": "\\App\\Services\\UserMetaService",
            "name": "UserMetaService",
            "summary": "Provides\u0020service\u0020to\u0020store\u0020user\u0020meta",
            "url": "classes/App-Services-UserMetaService.html"
        },                {
            "fqsen": "\\App\\Services\\UserMetaService\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "This\u0020method\u0020initializes\u0020the\u0020\u0060User\u0060\u0020object,\u0020retrieves\u0020the\u0020user\u0027s\u0020information,\u0020and\u0020ensures\u0020the\u0020user\u0020is\u0020valid.",
            "url": "classes/App-Services-UserMetaService.html#method___construct"
        },                {
            "fqsen": "\\App\\Services\\UserMetaService\u003A\u003Asave\u0028\u0029",
            "name": "save",
            "summary": "Save\u0020a\u0020user\u0020meta\u0020key\u002Dvalue\u0020pair.",
            "url": "classes/App-Services-UserMetaService.html#method_save"
        },                {
            "fqsen": "\\App\\Services\\UserMetaService\u003A\u003Afind\u0028\u0029",
            "name": "find",
            "summary": "Retrieve\u0020a\u0020meta\u0020value\u0020for\u0020a\u0020given\u0020user.",
            "url": "classes/App-Services-UserMetaService.html#method_find"
        },                {
            "fqsen": "\\App\\Services\\UserMetaService\u003A\u003A\u0024user",
            "name": "user",
            "summary": "",
            "url": "classes/App-Services-UserMetaService.html#property_user"
        },                {
            "fqsen": "\\App\\Services\\UserMetaService\u003A\u003A\u0024user_data",
            "name": "user_data",
            "summary": "",
            "url": "classes/App-Services-UserMetaService.html#property_user_data"
        },                {
            "fqsen": "\\App\\Services\\UserMetaService\u003A\u003A\u0024user_meta",
            "name": "user_meta",
            "summary": "",
            "url": "classes/App-Services-UserMetaService.html#property_user_meta"
        },                {
            "fqsen": "\\App\\ThirdParty\\TextEditor",
            "name": "TextEditor",
            "summary": "Provides\u0020base\u0020class\u0020for\u0020modular\u0020wysiwyg\u0020text\u0020editors",
            "url": "classes/App-ThirdParty-TextEditor.html"
        },                {
            "fqsen": "\\App\\ThirdParty\\TextEditor\u003A\u003A\u0024apiKey",
            "name": "apiKey",
            "summary": "",
            "url": "classes/App-ThirdParty-TextEditor.html#property_apiKey"
        },                {
            "fqsen": "\\App\\ThirdPArty\\TextEditorCKEditorCDN",
            "name": "TextEditorCKEditorCDN",
            "summary": "Implements\u0020the\u0020CKEditor\u0020CDN\u0020version\u0020using\u0020a\u0020apiKey.",
            "url": "classes/App-ThirdPArty-TextEditorCKEditorCDN.html"
        },                {
            "fqsen": "\\App\\ThirdPArty\\TextEditorCKEditorCDN\u003A\u003Aload_style\u0028\u0029",
            "name": "load_style",
            "summary": "Loads\u0020the\u0020stylesheet.",
            "url": "classes/App-ThirdPArty-TextEditorCKEditorCDN.html#method_load_style"
        },                {
            "fqsen": "\\App\\ThirdPArty\\TextEditorCKEditorCDN\u003A\u003Aload_script\u0028\u0029",
            "name": "load_script",
            "summary": "Loads\u0020or\u0020imports\u0020the\u0020external\u0020javascript\u0020libaries.",
            "url": "classes/App-ThirdPArty-TextEditorCKEditorCDN.html#method_load_script"
        },                {
            "fqsen": "\\App\\ThirdPArty\\TextEditorCKEditorCDN\u003A\u003Ainit_script\u0028\u0029",
            "name": "init_script",
            "summary": "Sets\u0020up\u0020the\u0020functions\u0020required\u0020to\u0020create\u0020a\u0020new\u0020instance\u0020of\u0020a\u0020textarea",
            "url": "classes/App-ThirdPArty-TextEditorCKEditorCDN.html#method_init_script"
        },                {
            "fqsen": "\\App\\ThirdPArty\\TextEditorCKEditorCDN\u003A\u003Aassign_editor\u0028\u0029",
            "name": "assign_editor",
            "summary": "Use\u0020this\u0020wrapper\u0020in\u0020the\u0020view\u0020template\u0020to\u0020create\u0020a\u0020new\u0020textarea\u0020instance",
            "url": "classes/App-ThirdPArty-TextEditorCKEditorCDN.html#method_assign_editor"
        },                {
            "fqsen": "\\App\\ThirdPArty\\TextEditorCKEditorCDN\u003A\u003Aget\u0028\u0029",
            "name": "get",
            "summary": "Use\u0020this\u0020wrapper\u0020in\u0020the\u0020view\u0020template\u0020to\u0020get\u0020the\u0020value\u0020of\u0020a\u0020textarea",
            "url": "classes/App-ThirdPArty-TextEditorCKEditorCDN.html#method_get"
        },                {
            "fqsen": "\\App\\ThirdPArty\\TextEditorCKEditorCDN\u003A\u003A\u0024apiKey",
            "name": "apiKey",
            "summary": "",
            "url": "classes/App-ThirdPArty-TextEditorCKEditorCDN.html#property_apiKey"
        },                {
            "fqsen": "\\App\\ThirdPArty\\TextEditorCKEditorGPL",
            "name": "TextEditorCKEditorGPL",
            "summary": "Implements\u0020the\u0020CKEditor\u0020GPL\u0020version\u0020using\u0020a\u0020apiKey.",
            "url": "classes/App-ThirdPArty-TextEditorCKEditorGPL.html"
        },                {
            "fqsen": "\\App\\ThirdPArty\\TextEditorCKEditorGPL\u003A\u003Aload_style\u0028\u0029",
            "name": "load_style",
            "summary": "Loads\u0020the\u0020stylesheet.",
            "url": "classes/App-ThirdPArty-TextEditorCKEditorGPL.html#method_load_style"
        },                {
            "fqsen": "\\App\\ThirdPArty\\TextEditorCKEditorGPL\u003A\u003Aload_script\u0028\u0029",
            "name": "load_script",
            "summary": "Loads\u0020or\u0020imports\u0020the\u0020external\u0020javascript\u0020libaries.",
            "url": "classes/App-ThirdPArty-TextEditorCKEditorGPL.html#method_load_script"
        },                {
            "fqsen": "\\App\\ThirdPArty\\TextEditorCKEditorGPL\u003A\u003Ainit_script\u0028\u0029",
            "name": "init_script",
            "summary": "Sets\u0020up\u0020the\u0020functions\u0020required\u0020to\u0020create\u0020a\u0020new\u0020instance\u0020of\u0020a\u0020textarea",
            "url": "classes/App-ThirdPArty-TextEditorCKEditorGPL.html#method_init_script"
        },                {
            "fqsen": "\\App\\ThirdPArty\\TextEditorCKEditorGPL\u003A\u003Aassign_editor\u0028\u0029",
            "name": "assign_editor",
            "summary": "Use\u0020this\u0020wrapper\u0020in\u0020the\u0020view\u0020template\u0020to\u0020create\u0020a\u0020new\u0020textarea\u0020instance",
            "url": "classes/App-ThirdPArty-TextEditorCKEditorGPL.html#method_assign_editor"
        },                {
            "fqsen": "\\App\\ThirdPArty\\TextEditorCKEditorGPL\u003A\u003Aget\u0028\u0029",
            "name": "get",
            "summary": "Use\u0020this\u0020wrapper\u0020in\u0020the\u0020view\u0020template\u0020to\u0020get\u0020the\u0020value\u0020of\u0020a\u0020textarea",
            "url": "classes/App-ThirdPArty-TextEditorCKEditorGPL.html#method_get"
        },                {
            "fqsen": "\\App\\ThirdPArty\\TextEditorCKEditorGPL\u003A\u003A\u0024apiKey",
            "name": "apiKey",
            "summary": "",
            "url": "classes/App-ThirdPArty-TextEditorCKEditorGPL.html#property_apiKey"
        },                {
            "fqsen": "\\App\\ThirdPArty\\TextEditorSummernote",
            "name": "TextEditorSummernote",
            "summary": "Implements\u0020the\u0020free\u0020Summernote\u0020CDN\u0020version.",
            "url": "classes/App-ThirdPArty-TextEditorSummernote.html"
        },                {
            "fqsen": "\\App\\ThirdPArty\\TextEditorSummernote\u003A\u003Aload_style\u0028\u0029",
            "name": "load_style",
            "summary": "Loads\u0020the\u0020stylesheet.",
            "url": "classes/App-ThirdPArty-TextEditorSummernote.html#method_load_style"
        },                {
            "fqsen": "\\App\\ThirdPArty\\TextEditorSummernote\u003A\u003Aload_script\u0028\u0029",
            "name": "load_script",
            "summary": "Loads\u0020or\u0020imports\u0020the\u0020external\u0020javascript\u0020libaries.",
            "url": "classes/App-ThirdPArty-TextEditorSummernote.html#method_load_script"
        },                {
            "fqsen": "\\App\\ThirdPArty\\TextEditorSummernote\u003A\u003Ainit_script\u0028\u0029",
            "name": "init_script",
            "summary": "Sets\u0020up\u0020the\u0020functions\u0020required\u0020to\u0020create\u0020a\u0020new\u0020instance\u0020of\u0020a\u0020textarea",
            "url": "classes/App-ThirdPArty-TextEditorSummernote.html#method_init_script"
        },                {
            "fqsen": "\\App\\ThirdPArty\\TextEditorSummernote\u003A\u003Aassign_editor\u0028\u0029",
            "name": "assign_editor",
            "summary": "Use\u0020this\u0020wrapper\u0020in\u0020the\u0020view\u0020template\u0020to\u0020create\u0020a\u0020new\u0020textarea\u0020instance",
            "url": "classes/App-ThirdPArty-TextEditorSummernote.html#method_assign_editor"
        },                {
            "fqsen": "\\App\\ThirdPArty\\TextEditorSummernote\u003A\u003Aget\u0028\u0029",
            "name": "get",
            "summary": "Use\u0020this\u0020wrapper\u0020in\u0020the\u0020view\u0020template\u0020to\u0020get\u0020the\u0020value\u0020of\u0020a\u0020textarea",
            "url": "classes/App-ThirdPArty-TextEditorSummernote.html#method_get"
        },                {
            "fqsen": "\\App\\ThirdPArty\\TextEditorSummernote\u003A\u003A\u0024apiKey",
            "name": "apiKey",
            "summary": "",
            "url": "classes/App-ThirdPArty-TextEditorSummernote.html#property_apiKey"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\App\\Controllers\\Admin",
            "name": "Admin",
            "summary": "",
            "url": "namespaces/app-controllers-admin.html"
        },                {
            "fqsen": "\\App\\Controllers\\Admin\\DashboardModules",
            "name": "DashboardModules",
            "summary": "",
            "url": "namespaces/app-controllers-admin-dashboardmodules.html"
        },                {
            "fqsen": "\\App\\Controllers",
            "name": "Controllers",
            "summary": "",
            "url": "namespaces/app-controllers.html"
        },                {
            "fqsen": "\\App",
            "name": "App",
            "summary": "",
            "url": "namespaces/app.html"
        },                {
            "fqsen": "\\App\\Controllers\\Front",
            "name": "Front",
            "summary": "",
            "url": "namespaces/app-controllers-front.html"
        },                {
            "fqsen": "\\App\\Controllers\\Front\\DashboardModules",
            "name": "DashboardModules",
            "summary": "",
            "url": "namespaces/app-controllers-front-dashboardmodules.html"
        },                {
            "fqsen": "\\App\\Filters",
            "name": "Filters",
            "summary": "",
            "url": "namespaces/app-filters.html"
        },                {
            "fqsen": "\\App\\Models",
            "name": "Models",
            "summary": "",
            "url": "namespaces/app-models.html"
        },                {
            "fqsen": "\\App\\Services",
            "name": "Services",
            "summary": "",
            "url": "namespaces/app-services.html"
        },                {
            "fqsen": "\\App\\ThirdParty",
            "name": "ThirdParty",
            "summary": "",
            "url": "namespaces/app-thirdparty.html"
        },                {
            "fqsen": "\\App\\ThirdPArty",
            "name": "ThirdPArty",
            "summary": "",
            "url": "namespaces/app-thirdparty.html"
        }            ]
);
